### PR TITLE
Update builders documentation

### LINKED ISSUE #266: TlsConnectorBuilder constructor
Hi,

I wanted to use the TLsConnectorBuilder to add a self signed certificate, and it appears that there's no default constructor for that struct. I know this is very minor, but I was wondering if either I didn't look properly, or if there was an opportunity to improve this api.

Currently I think I'd need to fill in all fields:
```rust
TlsConnectorBuilder {
  identity: None,
  min_protocol: None,
  ...
}.add_root_certificates(...).build()
```

And I'd like to write something similar to:
```rust
TlsConnectorBuilder::new().add_root_certificates(...).build()
```

I assume the default (either through `TlsConnectorBuilder::new()` or `impl Default for TlsConnectorBuilder`) would need to populate sensible values.

I'd be happy to contribute.

Thank you

### PR DESCRIPTION
**Pull request by rust1248**
Fixes #266 

Update the Builders documentation to make clearer how to construct them

### CODE REVIEW

**Comment by sfackler** [comment]
There are some rustfmt failures.

**Comment by rust1248** [comment]
These are not mine (I only updated the docs)

**Comment by sfackler** [comment]
The rustfmt failures are pointing at the docs you updated:

```diff
 }
 
 /// A builder for `TlsConnector`s.
-/// 
+///
 /// You can get one from [`TlsConnector::builder()`](TlsConnector::builder)
 pub struct TlsConnectorBuilder {
     identity: Option<Identity>,
Diff in /home/runner/work/rust-native-tls/rust-native-tls/src/lib.rs at line 5[19](https://github.com/sfackler/rust-native-tls/actions/runs/5342182950/jobs/9726590832?pr=271#step:4:21):
 }
 
 /// A builder for `TlsAcceptor`s.
-/// 
+///
 /// You can get one from [`TlsAcceptor::builder()`](TlsAcceptor::builder)
 pub struct TlsAcceptorBuilder {
     identity: Identity,
```

**Comment by rust1248** [comment]
@sfackler Sorry for that, I only saw the other error

I fixed them (I think)

**Pull request merged**
