### PR TITLE
deps: update openssl to 0.10

### PR DESCRIPTION
**Pull request by ragevou**
Signed-off-by: Alexandra Nikandrova <rage.iz.me@gmail.com>

### CODE REVIEW

**Comment by sfackler** [comment]
Duplicate of #68

**Comment by ignatenkobrain** [comment]
@sfackler Note that this PR is correct while #68 is just broken. Please reopen!

**Comment by ignatenkobrain** [comment]
@sfackler that code doesn't compile as-is on linux... and given that you don't test linux at all -- CI passed... But that PR is just broken.

**Comment by sfackler** [comment]
Oops, turned on Linux CI for pull requests.

**Comment by sfackler** [comment]
But in any case, this upgrade won't be landing for a little bit.

**Comment by ignatenkobrain** [comment]
@sfackler that's fine, I just want to have it opened because @ragevou spent some time on porting it.. And basically this is the version you are going to merge in future...

**Pull request closed without merging**
