### PR TITLE
Update to security-framework 0.4.1

### PR DESCRIPTION
**Pull request by metajack**

### CODE REVIEW

**Comment by sfackler** [comment]
Can you update the Rust version in CI to 1.36?

**Comment by metajack** [comment]
It needs 1.37 and I had to remove -D warnings, but this is now passing your CI.

**Comment by sfackler** [comment]
Thanks!

**Comment by metajack** [comment]
Any chance you could publish 0.2.4?

**Comment by sfackler** [comment]
Done!

**Pull request merged**
