### PR TITLE
use security-framework for iOS

### PR DESCRIPTION
**Pull request by king6cong**

### CODE REVIEW

**Comment by sfackler** [comment]
I'm a bit hesitant to land this until we have some integration testing - I think it should be possible to target the iOS simulator on the mac builders?

**Comment by king6cong** [comment]
@sfackler I'm currently working on a network api client SDK in rust for one app that will be available on multiple platforms(including iOS/Android). TLS support on iOS/Android is so important that I can't go any further without it. (HTTPS api is really fundamental). 

I wonder whether TLS for iOS/Android is ready by now ?

**Comment by king6cong** [comment]
So is https://github.com/tokio-rs/tokio-tls/pull/22

**Comment by sfackler** [comment]
Sure, I definitely understand the desire for this to work on iOS - I'm just looking for Travis to actually test to make sure it is in fact working, and will continue to do so over time.

**Comment by king6cong** [comment]
Thanks 👍

**Comment by azdlowry** [comment]
This doesn't build for me where target_os = "ios" as security_framework doesn't have keychain on ios.

**Comment by king6cong** [comment]
@azdlowry yeah, see https://github.com/sfackler/rust-native-tls/issues/44

**Comment by azdlowry** [comment]
This should be unnecessary now as the changes we're included in #50.

**Pull request closed without merging**
