### PR TITLE
deps: update openssl to 0.10

### PR DESCRIPTION
**Pull request by ragevou**
Signed-off-by: Alexandra Nikandrova <rage.iz.me@gmail.com>

---

Supersedes #69

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@sfackler seems that 1.19.0 is too old for bitflags 1.0... We need 1.12.0

**Comment by sfackler** [comment]
Yes, that's correct.

**Comment by jwilm** [comment]
Is this still being worked on?

**Comment by ignatenkobrain** [comment]
IMO PR is good enough.

**Pull request merged**
