### PR TITLE
Add examples from README to examples/

### PR DESCRIPTION
**Pull request by Byron**
That way, they are easy to compile for interested users and
run automatically as part of the test-suite.

### CODE REVIEW

**Comment by sfackler** [comment]
Looks like these lines need to be bumped: https://github.com/sfackler/rust-native-tls/blob/master/.travis.yml#L6 https://github.com/sfackler/rust-native-tls/blob/master/.travis.yml#L10

https://travis-ci.org/sfackler/rust-native-tls/jobs/204093322

**Comment by Byron** [comment]
@sfackler Thanks for the hints!
On an unrelated note: do you think it's possible to allow untrusted hosts, like those which are self-signed for the purpose of local testing, using this library?

**Comment by sfackler** [comment]
It is not yet - the functionality needs to be added to schannel-rs first. It's definitely something I do want to support though!

**Comment by Byron** [comment]
Perfect! Is  there a tracking issue I could subscribe to? I am trying to connect to a cassandra instance via TLS using `tokio-cassandra`, and am investigating libraries that support this. `rustls` would be been my favorite, but unfortunately its ciphers are too new :).

**Comment by sfackler** [comment]
#3

**Comment by Byron** [comment]
@sfackler - could you restart the travis jobs? It seems they failed for different reasons.

**Comment by sfackler** [comment]
Restarted Travis - The OpenSSL version will need to be updated in the appveyor config.

**Comment by Byron** [comment]
Thank you - the issue seems to be reproducible though.

@sfackler I am afraid I don't know what is going on here. The only change that might have caused this breakage on travis is to remove the v1.9 restriction for Rust. Appveyor needs a different version, as you say, but I don't know why this branch needs it while master apparently still works.
Looking into this it seems [the last build](https://travis-ci.org/sfackler/rust-native-tls/builds/192430849) ran successfully two months ago!
If you restarted that one, I would hope that similar issues crop up. Those could then be fixed in master, and I just rebase this PR onto it - et voilà.

What do you think :)?

**Comment by sfackler** [comment]
You should be able to rebase now

**Comment by Byron** [comment]
@sfackler Sorry for the great delay! The rebase was performed, and this branch looks like it can be merged now.

**Comment by sfackler** [comment]
Thanks!

**Pull request merged**
